/*
notifier

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.3.0
Contact: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RemoveChannelBody struct for RemoveChannelBody
type RemoveChannelBody struct {
	UserId string `json:"user_id"`
	ServiceId string `json:"service_id"`
}

// NewRemoveChannelBody instantiates a new RemoveChannelBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveChannelBody(userId string, serviceId string) *RemoveChannelBody {
	this := RemoveChannelBody{}
	this.UserId = userId
	this.ServiceId = serviceId
	return &this
}

// NewRemoveChannelBodyWithDefaults instantiates a new RemoveChannelBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveChannelBodyWithDefaults() *RemoveChannelBody {
	this := RemoveChannelBody{}
	return &this
}

// GetUserId returns the UserId field value
func (o *RemoveChannelBody) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *RemoveChannelBody) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *RemoveChannelBody) SetUserId(v string) {
	o.UserId = v
}

// GetServiceId returns the ServiceId field value
func (o *RemoveChannelBody) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *RemoveChannelBody) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *RemoveChannelBody) SetServiceId(v string) {
	o.ServiceId = v
}

func (o RemoveChannelBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	if true {
		toSerialize["service_id"] = o.ServiceId
	}
	return json.Marshal(toSerialize)
}

type NullableRemoveChannelBody struct {
	value *RemoveChannelBody
	isSet bool
}

func (v NullableRemoveChannelBody) Get() *RemoveChannelBody {
	return v.value
}

func (v *NullableRemoveChannelBody) Set(val *RemoveChannelBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveChannelBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveChannelBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveChannelBody(val *RemoveChannelBody) *NullableRemoveChannelBody {
	return &NullableRemoveChannelBody{value: val, isSet: true}
}

func (v NullableRemoveChannelBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveChannelBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


