/*
notifier

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.1
Contact: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddEmailChannelBody struct for AddEmailChannelBody
type AddEmailChannelBody struct {
	UserId string `json:"user_id"`
	Email string `json:"email"`
}

// NewAddEmailChannelBody instantiates a new AddEmailChannelBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddEmailChannelBody(userId string, email string) *AddEmailChannelBody {
	this := AddEmailChannelBody{}
	this.UserId = userId
	this.Email = email
	return &this
}

// NewAddEmailChannelBodyWithDefaults instantiates a new AddEmailChannelBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddEmailChannelBodyWithDefaults() *AddEmailChannelBody {
	this := AddEmailChannelBody{}
	return &this
}

// GetUserId returns the UserId field value
func (o *AddEmailChannelBody) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AddEmailChannelBody) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AddEmailChannelBody) SetUserId(v string) {
	o.UserId = v
}

// GetEmail returns the Email field value
func (o *AddEmailChannelBody) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AddEmailChannelBody) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AddEmailChannelBody) SetEmail(v string) {
	o.Email = v
}

func (o AddEmailChannelBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableAddEmailChannelBody struct {
	value *AddEmailChannelBody
	isSet bool
}

func (v NullableAddEmailChannelBody) Get() *AddEmailChannelBody {
	return v.value
}

func (v *NullableAddEmailChannelBody) Set(val *AddEmailChannelBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAddEmailChannelBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAddEmailChannelBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddEmailChannelBody(val *AddEmailChannelBody) *NullableAddEmailChannelBody {
	return &NullableAddEmailChannelBody{value: val, isSet: true}
}

func (v NullableAddEmailChannelBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddEmailChannelBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


