/*
notifier

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.2
Contact: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetTelegramChatIdBody struct for GetTelegramChatIdBody
type GetTelegramChatIdBody struct {
	TelegramUsername string `json:"telegram_username"`
	UserId string `json:"user_id"`
}

// NewGetTelegramChatIdBody instantiates a new GetTelegramChatIdBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTelegramChatIdBody(telegramUsername string, userId string) *GetTelegramChatIdBody {
	this := GetTelegramChatIdBody{}
	this.TelegramUsername = telegramUsername
	this.UserId = userId
	return &this
}

// NewGetTelegramChatIdBodyWithDefaults instantiates a new GetTelegramChatIdBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTelegramChatIdBodyWithDefaults() *GetTelegramChatIdBody {
	this := GetTelegramChatIdBody{}
	return &this
}

// GetTelegramUsername returns the TelegramUsername field value
func (o *GetTelegramChatIdBody) GetTelegramUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TelegramUsername
}

// GetTelegramUsernameOk returns a tuple with the TelegramUsername field value
// and a boolean to check if the value has been set.
func (o *GetTelegramChatIdBody) GetTelegramUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TelegramUsername, true
}

// SetTelegramUsername sets field value
func (o *GetTelegramChatIdBody) SetTelegramUsername(v string) {
	o.TelegramUsername = v
}

// GetUserId returns the UserId field value
func (o *GetTelegramChatIdBody) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GetTelegramChatIdBody) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GetTelegramChatIdBody) SetUserId(v string) {
	o.UserId = v
}

func (o GetTelegramChatIdBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["telegram_username"] = o.TelegramUsername
	}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	return json.Marshal(toSerialize)
}

type NullableGetTelegramChatIdBody struct {
	value *GetTelegramChatIdBody
	isSet bool
}

func (v NullableGetTelegramChatIdBody) Get() *GetTelegramChatIdBody {
	return v.value
}

func (v *NullableGetTelegramChatIdBody) Set(val *GetTelegramChatIdBody) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTelegramChatIdBody) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTelegramChatIdBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTelegramChatIdBody(val *GetTelegramChatIdBody) *NullableGetTelegramChatIdBody {
	return &NullableGetTelegramChatIdBody{value: val, isSet: true}
}

func (v NullableGetTelegramChatIdBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTelegramChatIdBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


