/*
notifier

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.2
Contact: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SendNotificationBody struct for SendNotificationBody
type SendNotificationBody struct {
	Subject string `json:"subject"`
	UserId string `json:"user_id"`
	Message string `json:"message"`
}

// NewSendNotificationBody instantiates a new SendNotificationBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendNotificationBody(subject string, userId string, message string) *SendNotificationBody {
	this := SendNotificationBody{}
	this.Subject = subject
	this.UserId = userId
	this.Message = message
	return &this
}

// NewSendNotificationBodyWithDefaults instantiates a new SendNotificationBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendNotificationBodyWithDefaults() *SendNotificationBody {
	this := SendNotificationBody{}
	return &this
}

// GetSubject returns the Subject field value
func (o *SendNotificationBody) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *SendNotificationBody) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *SendNotificationBody) SetSubject(v string) {
	o.Subject = v
}

// GetUserId returns the UserId field value
func (o *SendNotificationBody) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *SendNotificationBody) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *SendNotificationBody) SetUserId(v string) {
	o.UserId = v
}

// GetMessage returns the Message field value
func (o *SendNotificationBody) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SendNotificationBody) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SendNotificationBody) SetMessage(v string) {
	o.Message = v
}

func (o SendNotificationBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["subject"] = o.Subject
	}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableSendNotificationBody struct {
	value *SendNotificationBody
	isSet bool
}

func (v NullableSendNotificationBody) Get() *SendNotificationBody {
	return v.value
}

func (v *NullableSendNotificationBody) Set(val *SendNotificationBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSendNotificationBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSendNotificationBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendNotificationBody(val *SendNotificationBody) *NullableSendNotificationBody {
	return &NullableSendNotificationBody{value: val, isSet: true}
}

func (v NullableSendNotificationBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendNotificationBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


