/*
notifier

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2.1
Contact: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddTelegramChannelBody struct for AddTelegramChannelBody
type AddTelegramChannelBody struct {
	TelegramUsername string `json:"telegram_username"`
	UserId string `json:"user_id"`
}

// NewAddTelegramChannelBody instantiates a new AddTelegramChannelBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTelegramChannelBody(telegramUsername string, userId string) *AddTelegramChannelBody {
	this := AddTelegramChannelBody{}
	this.TelegramUsername = telegramUsername
	this.UserId = userId
	return &this
}

// NewAddTelegramChannelBodyWithDefaults instantiates a new AddTelegramChannelBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTelegramChannelBodyWithDefaults() *AddTelegramChannelBody {
	this := AddTelegramChannelBody{}
	return &this
}

// GetTelegramUsername returns the TelegramUsername field value
func (o *AddTelegramChannelBody) GetTelegramUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TelegramUsername
}

// GetTelegramUsernameOk returns a tuple with the TelegramUsername field value
// and a boolean to check if the value has been set.
func (o *AddTelegramChannelBody) GetTelegramUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TelegramUsername, true
}

// SetTelegramUsername sets field value
func (o *AddTelegramChannelBody) SetTelegramUsername(v string) {
	o.TelegramUsername = v
}

// GetUserId returns the UserId field value
func (o *AddTelegramChannelBody) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AddTelegramChannelBody) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AddTelegramChannelBody) SetUserId(v string) {
	o.UserId = v
}

func (o AddTelegramChannelBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["telegram_username"] = o.TelegramUsername
	}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	return json.Marshal(toSerialize)
}

type NullableAddTelegramChannelBody struct {
	value *AddTelegramChannelBody
	isSet bool
}

func (v NullableAddTelegramChannelBody) Get() *AddTelegramChannelBody {
	return v.value
}

func (v *NullableAddTelegramChannelBody) Set(val *AddTelegramChannelBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTelegramChannelBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTelegramChannelBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTelegramChannelBody(val *AddTelegramChannelBody) *NullableAddTelegramChannelBody {
	return &NullableAddTelegramChannelBody{value: val, isSet: true}
}

func (v NullableAddTelegramChannelBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTelegramChannelBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


