/*
notifier

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.3.2
Contact: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddChannelBody struct for AddChannelBody
type AddChannelBody struct {
	ServiceId string `json:"service_id"`
	ServiceUsername string `json:"service_username"`
	UserId string `json:"user_id"`
}

// NewAddChannelBody instantiates a new AddChannelBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddChannelBody(serviceId string, serviceUsername string, userId string) *AddChannelBody {
	this := AddChannelBody{}
	this.ServiceId = serviceId
	this.ServiceUsername = serviceUsername
	this.UserId = userId
	return &this
}

// NewAddChannelBodyWithDefaults instantiates a new AddChannelBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddChannelBodyWithDefaults() *AddChannelBody {
	this := AddChannelBody{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *AddChannelBody) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *AddChannelBody) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *AddChannelBody) SetServiceId(v string) {
	o.ServiceId = v
}

// GetServiceUsername returns the ServiceUsername field value
func (o *AddChannelBody) GetServiceUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceUsername
}

// GetServiceUsernameOk returns a tuple with the ServiceUsername field value
// and a boolean to check if the value has been set.
func (o *AddChannelBody) GetServiceUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceUsername, true
}

// SetServiceUsername sets field value
func (o *AddChannelBody) SetServiceUsername(v string) {
	o.ServiceUsername = v
}

// GetUserId returns the UserId field value
func (o *AddChannelBody) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AddChannelBody) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AddChannelBody) SetUserId(v string) {
	o.UserId = v
}

func (o AddChannelBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_id"] = o.ServiceId
	}
	if true {
		toSerialize["service_username"] = o.ServiceUsername
	}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	return json.Marshal(toSerialize)
}

type NullableAddChannelBody struct {
	value *AddChannelBody
	isSet bool
}

func (v NullableAddChannelBody) Get() *AddChannelBody {
	return v.value
}

func (v *NullableAddChannelBody) Set(val *AddChannelBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAddChannelBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAddChannelBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddChannelBody(val *AddChannelBody) *NullableAddChannelBody {
	return &NullableAddChannelBody{value: val, isSet: true}
}

func (v NullableAddChannelBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddChannelBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


